#n1 = input('Digite algo: ')
#print('O tipo primitivo deste valor é', type(n1))
#print('Tem só espaços?', n1.istitle())
#print('Está capitalizada?', n1.isprintable())
#print('Está maiúscula?', n1.isupper())
#print('Está minúscula?', n1.islower())
#print('É número?', n1.isnumeric())
#print('É alfabético?', n1.isalpha())
#print('É alfanumérico?', n1.isalnum())

n1 = input('Digite algo: ')
print('O tipo primitivo deste valor é {}.'.format(type(n1)))
print('Tem só espaços? {}'.format(n1.isspace()))
print('Está capitalizda? {}'.format(n1.istitle()))
print('Está maiúscula? {}'.format(n1.isupper()))
print('Está minúscula? {}'.format(n1.islower()))
print('É numero? {}'.format(n1.isnumeric()))
print('É alfabético? {}'.format(n1.isalpha()))
print('É alfanumérico? {}' .format(n1.isalnum()))
